package main

// +build ignore

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"sort"

	"github.com/cirbo-lang/cirbo/units"

	"github.com/cirbo-lang/cirbo/cbty"
)

func main() {
	f := openOutputFile()

	fmt.Fprintln(f, "package cty")
	fmt.Fprintln(f, "/////////////////")
	fmt.Fprintln(f, "// Generated by generate/generate_number_named_acc.go. DO NOT EDIT.")
	fmt.Fprintln(f, "/////////////////\n")

	var names []string
	dims := cbty.QuantityDimensionalities()
	for name := range cbty.QuantityDimensionalities() {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		dim := dims[name]
		if dim == (units.Dimensionality{}) {
			fmt.Fprintf(f, "// %s is the dimensionless quantity type.\n", name)
		} else {
			fmt.Fprintf(f, "// %s is a quantity type of dimensionality %s.\n", name, dim)
		}
		fmt.Fprintf(f, "var %s Type = QuantityByName(%q)\n", name, name)
	}
}

func openOutputFile() io.Writer {
	outfile, err := os.Create("number_named_acc.go")
	if err != nil {
		log.Fatal(err)
	}
	// Pipe output to gofmt.
	gofmt := exec.Command("gofmt")
	fd, err := gofmt.StdinPipe()
	if err != nil {
		log.Fatal(err)
	}
	gofmt.Stdout = outfile
	gofmt.Stderr = os.Stderr
	err = gofmt.Start()
	if err != nil {
		log.Fatal(err)
	}
	return fd
}
