package cbty

/////////////////
// Generated by generate/generate_number_named_acc.go. DO NOT EDIT.
/////////////////

// Angle is a quantity type of dimensionality [angle].
var Angle Type = QuantityByName("Angle")

// AngularSpeed is a quantity type of dimensionality [angle][T]⁻¹.
var AngularSpeed Type = QuantityByName("AngularSpeed")

// Area is a quantity type of dimensionality [L]².
var Area Type = QuantityByName("Area")

// Capacitance is a quantity type of dimensionality [I]²[T]⁴[M]⁻¹[L]⁻².
var Capacitance Type = QuantityByName("Capacitance")

// Charge is a quantity type of dimensionality [I][T].
var Charge Type = QuantityByName("Charge")

// Conductance is a quantity type of dimensionality [I]²[T]³[M]⁻¹[L]⁻².
var Conductance Type = QuantityByName("Conductance")

// Conductivity is a quantity type of dimensionality [I]²[T]³[M]⁻¹[L]⁻³.
var Conductivity Type = QuantityByName("Conductivity")

// Current is a quantity type of dimensionality [I].
var Current Type = QuantityByName("Current")

// Force is a quantity type of dimensionality [M][L][T]⁻².
var Force Type = QuantityByName("Force")

// Frequency is a quantity type of dimensionality [T]⁻¹.
var Frequency Type = QuantityByName("Frequency")

// Illuminance is a quantity type of dimensionality [J][L]⁻².
var Illuminance Type = QuantityByName("Illuminance")

// Inductance is a quantity type of dimensionality [M][L]²[I]⁻²[T]⁻².
var Inductance Type = QuantityByName("Inductance")

// Length is a quantity type of dimensionality [L].
var Length Type = QuantityByName("Length")

// LuminousIntensity is a quantity type of dimensionality [J].
var LuminousIntensity Type = QuantityByName("LuminousIntensity")

// Mass is a quantity type of dimensionality [M].
var Mass Type = QuantityByName("Mass")

// Momentum is a quantity type of dimensionality [M][L][T]⁻¹.
var Momentum Type = QuantityByName("Momentum")

// Number is the dimensionless quantity type.
var Number Type = QuantityByName("Number")

// Power is a quantity type of dimensionality [M][L]²[T]⁻³.
var Power Type = QuantityByName("Power")

// Resistance is a quantity type of dimensionality [M][L]²[I]⁻²[T]⁻³.
var Resistance Type = QuantityByName("Resistance")

// Resistivity is a quantity type of dimensionality [M][L]³[I]⁻²[T]⁻³.
var Resistivity Type = QuantityByName("Resistivity")

// Speed is a quantity type of dimensionality [L][T]⁻¹.
var Speed Type = QuantityByName("Speed")

// Time is a quantity type of dimensionality [T].
var Time Type = QuantityByName("Time")

// Voltage is a quantity type of dimensionality [M][L]²[I]⁻¹[T]⁻³.
var Voltage Type = QuantityByName("Voltage")
