// Code generated by "stringer -type=ERCType"; DO NOT EDIT.

package cbo

import "fmt"

const (
	_ERCType_name_0 = "Passive"
	_ERCType_name_1 = "Power"
	_ERCType_name_2 = "Signal"
)

var (
	_ERCType_index_0 = [...]uint8{0, 7}
	_ERCType_index_1 = [...]uint8{0, 5}
	_ERCType_index_2 = [...]uint8{0, 6}
)

func (i ERCType) String() string {
	switch {
	case i == 0:
		return _ERCType_name_0
	case i == 80:
		return _ERCType_name_1
	case i == 83:
		return _ERCType_name_2
	default:
		return fmt.Sprintf("ERCType(%d)", i)
	}
}
