// Code generated by "stringer -type=TerminalOutputType"; DO NOT EDIT.

package cbo

import "fmt"

const (
	_TerminalOutputType_name_0 = "NoOutput"
	_TerminalOutputType_name_1 = "OpenCollector"
	_TerminalOutputType_name_2 = "OpenEmitter"
	_TerminalOutputType_name_3 = "PushPull"
	_TerminalOutputType_name_4 = "Tristate"
)

var (
	_TerminalOutputType_index_0 = [...]uint8{0, 8}
	_TerminalOutputType_index_1 = [...]uint8{0, 13}
	_TerminalOutputType_index_2 = [...]uint8{0, 11}
	_TerminalOutputType_index_3 = [...]uint8{0, 8}
	_TerminalOutputType_index_4 = [...]uint8{0, 8}
)

func (i TerminalOutputType) String() string {
	switch {
	case i == 0:
		return _TerminalOutputType_name_0
	case i == 67:
		return _TerminalOutputType_name_1
	case i == 69:
		return _TerminalOutputType_name_2
	case i == 80:
		return _TerminalOutputType_name_3
	case i == 177:
		return _TerminalOutputType_name_4
	default:
		return fmt.Sprintf("TerminalOutputType(%d)", i)
	}
}
