// Code generated by "stringer -type=TerminalType"; DO NOT EDIT.

package ast

import "fmt"

const (
	_TerminalType_name_0 = "Passive"
	_TerminalType_name_1 = "Power"
	_TerminalType_name_2 = "Signal"
)

var (
	_TerminalType_index_0 = [...]uint8{0, 7}
	_TerminalType_index_1 = [...]uint8{0, 5}
	_TerminalType_index_2 = [...]uint8{0, 6}
)

func (i TerminalType) String() string {
	switch {
	case i == 0:
		return _TerminalType_name_0
	case i == 80:
		return _TerminalType_name_1
	case i == 83:
		return _TerminalType_name_2
	default:
		return fmt.Sprintf("TerminalType(%d)", i)
	}
}
