// Code generated by "stringer -type=TerminalRole"; DO NOT EDIT.

package ast

import "fmt"

const (
	_TerminalRole_name_0 = "NoRole"
	_TerminalRole_name_1 = "Follower"
	_TerminalRole_name_2 = "Leader"
)

var (
	_TerminalRole_index_0 = [...]uint8{0, 6}
	_TerminalRole_index_1 = [...]uint8{0, 8}
	_TerminalRole_index_2 = [...]uint8{0, 6}
)

func (i TerminalRole) String() string {
	switch {
	case i == 0:
		return _TerminalRole_name_0
	case i == 70:
		return _TerminalRole_name_1
	case i == 76:
		return _TerminalRole_name_2
	default:
		return fmt.Sprintf("TerminalRole(%d)", i)
	}
}
