// Code generated by "stringer -type=TerminalDir"; DO NOT EDIT.

package ast

import "fmt"

const (
	_TerminalDir_name_0 = "Undirected"
	_TerminalDir_name_1 = "Bidirectional"
	_TerminalDir_name_2 = "Input"
	_TerminalDir_name_3 = "Output"
)

var (
	_TerminalDir_index_0 = [...]uint8{0, 10}
	_TerminalDir_index_1 = [...]uint8{0, 13}
	_TerminalDir_index_2 = [...]uint8{0, 5}
	_TerminalDir_index_3 = [...]uint8{0, 6}
)

func (i TerminalDir) String() string {
	switch {
	case i == 0:
		return _TerminalDir_name_0
	case i == 66:
		return _TerminalDir_name_1
	case i == 73:
		return _TerminalDir_name_2
	case i == 79:
		return _TerminalDir_name_3
	default:
		return fmt.Sprintf("TerminalDir(%d)", i)
	}
}
