package cty

/////////////////
// Generated by generate/generate_number_named_acc.go. DO NOT EDIT.
/////////////////

// Angle is a quantity type of dimensionality [angle].
var Angle Type

// AngularSpeed is a quantity type of dimensionality [angle][T]⁻¹.
var AngularSpeed Type

// Area is a quantity type of dimensionality [L]².
var Area Type

// Capacitance is a quantity type of dimensionality [I]²[T]⁴[L]⁻²[M]⁻¹.
var Capacitance Type

// Current is a quantity type of dimensionality [I].
var Current Type

// Force is a quantity type of dimensionality [M][L][T]⁻².
var Force Type

// Frequency is a quantity type of dimensionality [T]⁻¹.
var Frequency Type

// Illuminance is a quantity type of dimensionality [J][L]⁻².
var Illuminance Type

// Inductance is a quantity type of dimensionality [M][L]²[T]⁻²[I]⁻².
var Inductance Type

// Length is a quantity type of dimensionality [L].
var Length Type

// LuminousIntensity is a quantity type of dimensionality [J].
var LuminousIntensity Type

// Mass is a quantity type of dimensionality [M].
var Mass Type

// Momentum is a quantity type of dimensionality [M][L][T]⁻¹.
var Momentum Type

// Number is a quantity type of dimensionality .
var Number Type

// Power is a quantity type of dimensionality [M][L]²[T]⁻³.
var Power Type

// Resistance is a quantity type of dimensionality [M][L]²[T]⁻³[I]⁻².
var Resistance Type

// Speed is a quantity type of dimensionality [L][T]⁻¹.
var Speed Type

// Time is a quantity type of dimensionality [T].
var Time Type

// Voltage is a quantity type of dimensionality [M][L]²[T]⁻³[I]⁻¹.
var Voltage Type

func init() {
	Angle = namedNumberTypes["Angle"]
	AngularSpeed = namedNumberTypes["AngularSpeed"]
	Area = namedNumberTypes["Area"]
	Capacitance = namedNumberTypes["Capacitance"]
	Current = namedNumberTypes["Current"]
	Force = namedNumberTypes["Force"]
	Frequency = namedNumberTypes["Frequency"]
	Illuminance = namedNumberTypes["Illuminance"]
	Inductance = namedNumberTypes["Inductance"]
	Length = namedNumberTypes["Length"]
	LuminousIntensity = namedNumberTypes["LuminousIntensity"]
	Mass = namedNumberTypes["Mass"]
	Momentum = namedNumberTypes["Momentum"]
	Number = namedNumberTypes["Number"]
	Power = namedNumberTypes["Power"]
	Resistance = namedNumberTypes["Resistance"]
	Speed = namedNumberTypes["Speed"]
	Time = namedNumberTypes["Time"]
	Voltage = namedNumberTypes["Voltage"]
}
