package globals

/////////////////
// Generated by generate/generate_types_gen.go. DO NOT EDIT.
/////////////////

import (
	"github.com/cirbo-lang/cirbo/cty"
)

var Angle cty.Value = cty.TypeTypeVal(cty.Angle)
var AngularSpeed cty.Value = cty.TypeTypeVal(cty.AngularSpeed)
var Area cty.Value = cty.TypeTypeVal(cty.Area)
var Capacitance cty.Value = cty.TypeTypeVal(cty.Capacitance)
var Conductance cty.Value = cty.TypeTypeVal(cty.Conductance)
var Conductivity cty.Value = cty.TypeTypeVal(cty.Conductivity)
var Current cty.Value = cty.TypeTypeVal(cty.Current)
var Force cty.Value = cty.TypeTypeVal(cty.Force)
var Frequency cty.Value = cty.TypeTypeVal(cty.Frequency)
var Illuminance cty.Value = cty.TypeTypeVal(cty.Illuminance)
var Inductance cty.Value = cty.TypeTypeVal(cty.Inductance)
var Length cty.Value = cty.TypeTypeVal(cty.Length)
var LuminousIntensity cty.Value = cty.TypeTypeVal(cty.LuminousIntensity)
var Mass cty.Value = cty.TypeTypeVal(cty.Mass)
var Momentum cty.Value = cty.TypeTypeVal(cty.Momentum)
var Number cty.Value = cty.TypeTypeVal(cty.Number)
var Power cty.Value = cty.TypeTypeVal(cty.Power)
var Resistance cty.Value = cty.TypeTypeVal(cty.Resistance)
var Resistivity cty.Value = cty.TypeTypeVal(cty.Resistivity)
var Speed cty.Value = cty.TypeTypeVal(cty.Speed)
var Time cty.Value = cty.TypeTypeVal(cty.Time)
var Voltage cty.Value = cty.TypeTypeVal(cty.Voltage)
