package globals

/////////////////
// Generated by generate/generate_types_gen.go. DO NOT EDIT.
/////////////////

import (
	"github.com/cirbo-lang/cirbo/cbty"
)

var Angle cbty.Value = cbty.TypeTypeVal(cbty.Angle)
var AngularSpeed cbty.Value = cbty.TypeTypeVal(cbty.AngularSpeed)
var Area cbty.Value = cbty.TypeTypeVal(cbty.Area)
var Capacitance cbty.Value = cbty.TypeTypeVal(cbty.Capacitance)
var Charge cbty.Value = cbty.TypeTypeVal(cbty.Charge)
var Conductance cbty.Value = cbty.TypeTypeVal(cbty.Conductance)
var Conductivity cbty.Value = cbty.TypeTypeVal(cbty.Conductivity)
var Current cbty.Value = cbty.TypeTypeVal(cbty.Current)
var Force cbty.Value = cbty.TypeTypeVal(cbty.Force)
var Frequency cbty.Value = cbty.TypeTypeVal(cbty.Frequency)
var Illuminance cbty.Value = cbty.TypeTypeVal(cbty.Illuminance)
var Inductance cbty.Value = cbty.TypeTypeVal(cbty.Inductance)
var Length cbty.Value = cbty.TypeTypeVal(cbty.Length)
var LuminousIntensity cbty.Value = cbty.TypeTypeVal(cbty.LuminousIntensity)
var Mass cbty.Value = cbty.TypeTypeVal(cbty.Mass)
var Momentum cbty.Value = cbty.TypeTypeVal(cbty.Momentum)
var Number cbty.Value = cbty.TypeTypeVal(cbty.Number)
var Power cbty.Value = cbty.TypeTypeVal(cbty.Power)
var Resistance cbty.Value = cbty.TypeTypeVal(cbty.Resistance)
var Resistivity cbty.Value = cbty.TypeTypeVal(cbty.Resistivity)
var Speed cbty.Value = cbty.TypeTypeVal(cbty.Speed)
var Time cbty.Value = cbty.TypeTypeVal(cbty.Time)
var Voltage cbty.Value = cbty.TypeTypeVal(cbty.Voltage)
